from playwright.sync_api import sync_playwright
from common import APP, launch
res = []
def chk(n, c, extra=''): res.append((n, bool(c), extra)); print(('OK  ' if c else 'FAIL'), n, extra)
with sync_playwright() as p:
    b = launch(p)
    for n, tr in (('1', "['43']"), ('2', "['43','44']"), ('4', "['33','43','44','65']")):
        ctx = b.new_context(viewport={'width': 1366, 'height': 768}); pages = []
        ctx.on('page', lambda pg: pages.append(pg))
        pg = ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.on('console', lambda m: errs.append('console:' + m.text) if (m.type == 'error' and 'ERR_' not in m.text and 'Failed to load resource' not in m.text) else None)
        pg.goto(APP)
        pg.evaluate(f"S.trupps={tr}; S.mode='limit'; S.limit=15; saveS()"); pg.reload()
        pg.click('#go'); pg.wait_for_timeout(300)
        chk(n + ' Start ohne Namen bleibt auf Startseite', pg.evaluate("document.querySelector('#start').classList.contains('on')"))
        pg.fill('#team1', 'Test'); pg.click('#go'); pg.wait_for_timeout(800)
        chk(n + ' Spiel sichtbar', pg.evaluate("document.querySelector('#game').classList.contains('on')"))
        nb = pg.evaluate("document.querySelectorAll('#game .tbox').length"); chk(n + ' Anzahl Einheiten-Boxen', nb == int(n), str(nb))
        chk(n + ' Module gesperrt', pg.evaluate("document.querySelectorAll('#game .tbox.tlock').length") == nb)
        chk(n + ' Uhr steht', pg.evaluate("G.t0===null"))
        pg.evaluate("onError(G.mods[0])"); pg.wait_for_timeout(1200)
        chk(n + ' Uhr laeuft nicht vor Schritt 1', pg.evaluate("G.t0===null"))
        pg.click('#fcAll'); pg.wait_for_timeout(1500)
        chk(n + ' Uhr laeuft nach Schritt 1', pg.evaluate("G.t0!==null"))
        chk(n + ' Sperre weg', pg.evaluate("document.querySelectorAll('#game .tbox.tlock').length") == 0)
        pg.evaluate("""()=>{G.tl.forEach((e,ti)=>{[1,2].forEach((s,k)=>{const ids=[1+k*2,2+k*2];tqApply('t'+ti+s,{t:'ans',r:G.run,e:e,s:s,a:[[ids[0],DATA.fragen[ids[0]-1].ok],[ids[1],(DATA.fragen[ids[1]-1].ok+1)%3]]})})})}""")
        pg.wait_for_timeout(300)
        chk(n + ' Fragen gewertet', pg.evaluate("G.errs>=G.tl.length*2"), pg.evaluate("String(G.errs)+' Fehler, pen '+G.pen"))
        pg.evaluate("tqApply('a1',{t:'arr',r:G.run,e:G.tl[0],s:DATA.rgStation})"); pg.wait_for_timeout(200)
        chk(n + ' Station 3 Meldung ok', pg.evaluate("G.tk[0]==='rg'||G.tk[0]==='rgdone'||G.stDone[0].has(3)"))
        pg.evaluate("G.mods.forEach(m=>onSolved(m))"); pg.wait_for_timeout(1500)
        chk(n + ' Ergebnis sichtbar', pg.evaluate("document.querySelector('#result').classList.contains('on')"))
        chk(n + ' Ergebnis Lage gesichert', pg.evaluate("G.rec.ok===true"))
        chk(n + ' Tabelle gefuellt', len(pg.evaluate("document.querySelector('#rBody').innerText")) > 20)
        pages.clear(); pg.click('#rPdf'); pg.wait_for_timeout(1200)
        chk(n + ' Runde PDF oeffnet Tab', len(pages) >= 1)
        for q in pages: q.close()
        pg.click('#rEve'); pg.wait_for_timeout(500)
        chk(n + ' Abendauswertung', pg.evaluate("document.querySelector('#evening').classList.contains('on')||document.querySelector('#eBody').innerText.length>10"))
        pages.clear(); pg.click('#ePdf'); pg.wait_for_timeout(1200); chk(n + ' Abend PDF Tab', len(pages) >= 1)
        chk(n + ' keine JS-Fehler', not errs, '; '.join(errs)[:300])
        ctx.close()
    ctx = b.new_context(viewport={'width': 1366, 'height': 768}); pg = ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(APP); pg.evaluate("S.trupps=['43','44']; S.mode='limit'; S.limit=1; saveS()"); pg.reload()
    pg.fill('#team1', 'Z'); pg.click('#go'); pg.wait_for_timeout(500); pg.click('#fcAll'); pg.wait_for_timeout(500)
    pg.evaluate("G.t0=Date.now()-61000"); pg.wait_for_timeout(1500)
    chk('Zeitlimit beendet Runde', pg.evaluate("G.ended===true && G.rec.reason==='Zeit abgelaufen'"), pg.evaluate("G.rec&&G.rec.reason"))
    pg.click('#rAgain'); pg.wait_for_timeout(700); chk('Naechste Gruppe startet direkt', pg.evaluate("document.querySelector('#game').classList.contains('on') && G.t0===null && !G.ended"))
    pg.click('#gAbort'); pg.wait_for_timeout(200); pg.click('#gAbort'); pg.wait_for_timeout(700)
    chk('Abbruch zweistufig', pg.evaluate("G.ended===true && G.rec.reason==='Übung abgebrochen'"))
    chk('Einsatznummer laeuft hoch', pg.evaluate("G.nr.endsWith('_002')"), pg.evaluate("G.nr"))
    chk('keine JS-Fehler Z', not errs, '; '.join(errs))
    b.close()
fails = [r for r in res if not r[1]]
print('FAILS', fails); raise SystemExit(1 if fails else 0)
